module.exports = {
    imageSize: 4194304,
    shareTitle: "颜值榜第{0}就是我，要来一起比比颜值吗？",
    shareDesc: "",
    diameterMax: 110,
    diameterMin: 72,
    version: "9.0.1.07.18.16.43",
    appId: "wx75eafb1c5a558694",
    qrCodeAddress: null,
    selfToken: !1,
    serverApi: {
        imageProcessUrl: "https://minisite-skill.msxiaobing.com/Api/ImageAnalyze/Process?service=CSYanzhiWeApp",
        imageUploadUrl: "https://mediaplatform.msxiaobing.com/Image/Upload",
        decryptUrl: "https://csweappprod.msxiaobing.com/api"
    },
    screenSpan: 134,
    anonymousAlias: "匿名用户",
    defaultWording: "此宝座尚在空缺中~快为本群颜值事业贡献力量吧！",
    emptyRankList: [{
        image: "../../images/default.png",
        name: null,
        score: null,
        corpus: null,
        ranking: 1,
        width: 110,
        height: 110,
        left: 0,
        top: 0
    }, {
        image: "../../images/default.png",
        name: null,
        score: null,
        corpus: null,
        ranking: 2,
        width: 72,
        height: 72,
        left: 0,
        top: 0
    }, {
        image: "../../images/default.png",
        name: null,
        score: null,
        corpus: null,
        ranking: 3,
        width: 72,
        height: 72,
        left: 0,
        top: 0
    }],
    defaultRankList: [{
        image: "../../images/defaultRank1.png",
        name: "Sherry",
        score: "10分",
        corpus: "荣登本群颜值之最！这颜值在此群完全找不到对手啊~",
        ranking: 1,
        width: 110,
        height: 110,
        left: 0,
        top: 0
    }, {
        image: "../../images/defaultRank2.png",
        name: "大胡子",
        score: "7分",
        corpus: "颜值越高，责任越大~这么高的颜值要承担的责任可不小呀~",
        ranking: 2,
        width: 72,
        height: 72,
        left: 0,
        top: 0
    }, {
        image: "../../images/defaultRank3.png",
        name: "兔兔长虎牙",
        score: "5分",
        corpus: "唉！长得太好看也是一种罪过..照镜子总被惊艳(⊙v⊙)",
        ranking: 3,
        width: 72,
        height: 72,
        left: 0,
        top: 0
    }],
    errorType: {
        netWorkError: "NetWorkError",
        imageUploadError: "ImageUploadError",
        imageProcessError: "ImageProcessError",
        sessionKeyGetError: "SessionKeyGetError",
        sessionKeyStoreError: "SessionKeyStoreError",
        decryptDataError: "DecryptDataError",
        groupRankReadError: "GroupRankReadError",
        groupRankWriteError: "GroupRankWriteError",
        shareInfoGetError: "ShareInfoGetError",
        shareFailError: "ShareFailError"
    }
};